spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SQL_HOST:localhost}:5432/postgres
    username: ${SQL_USERNAME:postgres}
    password: ${SQL_PASS:example}
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
server:
  port: 8080
application:
  admin:
    name: ${APP_ADMIN:iland@mail.ru}
    password: ${APP_ADMIN_PASS:123}